id = "beach"
name = "Beach"
surface_block = "sand"
filler_block = "sand"
generates_trees = false
tree_density_multiplier = 0.0
radius = 180.0
radius_variation = 40.0
spawn_chance = 0.0
min_height = 18
max_height = 26
min_height_limit = 16
max_height_limit = 24
base_slope_bias = 0.25
max_gradient = 12.0
footprint_multiplier = 1.0
flags = ["land", "beach"]
smooth_beaches = true
keep_original_terrain = 0.1
properties = ["temperate", "land", "ocean", "wet", "balanced"]

[soil_creep]
strength = 0.2
max_step = 1
max_depth = 2

[stripes]
enabled = false
block = "sand"
period = 4
thickness = 1
noise_threshold = 0.4

[water_fill]
enabled = false
block = "water"
max_depth = 0
