id = "desert"
name = "Desert"
surface_block = "sand"
filler_block = "sand"
generates_trees = false
tree_density_multiplier = 0.0
radius = 450.0
radius_variation = 120.0
spawn_chance = 1.0
min_height = 18
max_height = 48
roughness = 0.6 
hills = 0.3
min_height_limit = 20
max_height_limit = 52
base_slope_bias = 0.30
max_gradient = 14.0
footprint_multiplier = 1.0
flags = ["land"]
smooth_beaches = true
keep_original_terrain = 0.25
properties = ["hot", "dry", "land", "barren"]

[[transition_biomes]]
id = "beach"
chance = 1.0
width = 4
properties = ["ocean"]

max_sub_biome_count = 1.5
sub_biome_total_chance = 0.2

[[sub_biomes]]
id = "grasslands"
chance = 0.2
min_radius = 32.0
max_radius = 96.0

[soil_creep]
strength = 0.18
max_step = 1
max_depth = 2

[stripes]
enabled = true
block = "sand"
period = 6
thickness = 2
noise_threshold = 0.35

[water_fill]
enabled = false
block = "water"
max_depth = 0
