id = "desert"
name = "Desert"
surface_block = "sand"
filler_block = "sand"
generates_trees = false
tree_density_multiplier = 0.0
radius = 450.0
radius_variation = 120.0
spawn_chance = 1.0
min_height = 18
max_height = 48
base_slope_bias = 0.30
max_gradient = 14.0
footprint_multiplier = 1.0
flags = ["land"]
smooth_beaches = true
keep_original_terrain = 0.25

[soil_creep]
strength = 0.18
max_step = 1
max_depth = 2

[stripes]
enabled = true
block = "sand"
period = 6
thickness = 2
noise_threshold = 0.35

[water_fill]
enabled = false
block = "water"
max_depth = 0
