id = "forest"
name = "Forest"
surface_block = "grass"
filler_block = "grass"
generates_trees = true
tree_density_multiplier = 3.5
radius = 320.0
radius_variation = 80.0
spawn_chance = 1.2
min_height = 28
max_height = 62
base_slope_bias = 0.45
max_gradient = 9.0
footprint_multiplier = 1.0
flags = ["land"]
smooth_beaches = true
keep_original_terrain = 0.55

[coast]
range = 16.0
min_roughness_scale = 0.35
height_blend = 0.1

[soil_creep]
strength = 0.4
max_step = 2
max_depth = 3

[stripes]
enabled = false
block = "grass"
period = 5
thickness = 1
noise_threshold = 0.5

[water_fill]
enabled = false
block = "water"
max_depth = 0
