id = "grasslands"
name = "Grasslands"
surface_block = "grass"
filler_block = "grass"
generates_trees = false
tree_density_multiplier = 0.0
radius = 360.0
radius_variation = 90.0
spawn_chance = 1.1
min_height = 24
max_height = 52
base_slope_bias = 0.65
max_gradient = 6.0
footprint_multiplier = 1.0
flags = ["land"]
smooth_beaches = true
keep_original_terrain = 0.4

[soil_creep]
strength = 0.3
max_step = 2
max_depth = 4

[stripes]
enabled = false
block = "grass"
period = 6
thickness = 1
noise_threshold = 0.5

[water_fill]
enabled = false
block = "water"
max_depth = 0
