id = "little_mountains"
name = "Little Mountains"
surface_block = "grass"
filler_block = "stone"
generates_trees = false
tree_density_multiplier = 0.0
height_offset = 270.0
height_scale = 44.0
min_height = 30
max_height = 820
base_slope_bias = 0.10
max_gradient = 320.0
footprint_multiplier = 3.3
flags = ["land", "little_mountains"]
