id = "little_mountains"
name = "Little Mountains"
surface_block = "grass"
filler_block = "stone"
generates_trees = false
tree_density_multiplier = 0.0
radius = 220.0
radius_variation = 60.0
spawn_chance = 0.6
min_height = 70
max_height = 180
base_slope_bias = 0.08
max_gradient = 220.0
footprint_multiplier = 1.8
flags = ["land", "little_mountains"]
smooth_beaches = false
keep_original_terrain = 0.55

[soil_creep]
strength = 0.15
max_step = 1
max_depth = 2

[stripes]
enabled = true
block = "stone"
period = 4
thickness = 1
noise_threshold = 0.6

[water_fill]
enabled = false
block = "water"
max_depth = 0
