id = "ocean_shelf"
name = "Ocean Shelf"
surface_block = "sand"
filler_block = "sand"
generates_trees = false
tree_density_multiplier = 0.0
radius = 520.0
radius_variation = 0.0
fixed_radius = true
spawn_chance = 0.0
min_height = 10
max_height = 20
min_height_limit = 14
max_height_limit = 22
base_slope_bias = 0.35
max_gradient = 6.0
footprint_multiplier = 1.0
flags = ["ocean", "coastal"]
smooth_beaches = true
keep_original_terrain = 0.3
properties = ["temperate", "ocean", "land", "wet"]

[soil_creep]
strength = 0.18
max_step = 1
max_depth = 2

[stripes]
enabled = false
block = "sand"
period = 4
thickness = 1
noise_threshold = 0.35

[water_fill]
enabled = true
block = "water"
max_depth = 20
