id = "ocean"
name = "Ocean"
surface_block = "water"
filler_block = "water"
generates_trees = false
tree_density_multiplier = 0.0
radius = 520.0
radius_variation = 0.0
fixed_radius = true
spawn_chance = 1.4
min_height = -64
max_height = 12
min_height_limit = -64
max_height_limit = 20
base_slope_bias = 1.0
max_gradient = 1.0
footprint_multiplier = 1.0
flags = ["ocean"]
smooth_beaches = true
keep_original_terrain = 0.7
properties = ["temperate", "ocean", "wet", "balanced"]

[[transition_biomes]]
id = "beach"
chance = 1.0
width = 1
properties = ["land"]

[[transition_biomes]]
id = "ocean_shelf"
chance = 1.0
width = 3
properties = ["land"]

[soil_creep]
strength = 0.08
max_step = 1
max_depth = 2

[stripes]
enabled = false
block = "sand"
period = 4
thickness = 1
noise_threshold = 0.4

[water_fill]
enabled = true
block = "water"
max_depth = 32
